const type = {
  LOGIN_DATA: 'LOGIN_DATA',
  OWNERS_DATA: 'OWNERS_DATA',
  LOADING_PAGE: 'LOADING_PAGE',
  SET_RESULT: 'SET_RESULT',
  SET_SELECTED_RESULT: 'SET_SELECTED_RESULT'
}

export default type