const initialState = {
  'data': {
    'boxscore': {
      'linescore': {
        'inning_line_score': [
          {
            'inning': '1',
            'home': '3',
            'away': '2'
          },
          {
            'inning': '2',
            'home': '2',
            'away': '0'
          },
          {
            'inning': '3',
            'home': '0',
            'away': '0'
          },
          {
            'inning': '4',
            'home': '0',
            'away': '0'
          },
          {
            'inning': '5',
            'home': '1',
            'away': '0'
          },
          {
            'inning': '6',
            'home': '1',
            'away': '0'
          },
          {
            'inning': '7',
            'home': '0',
            'away': '0'
          },
          {
            'inning': '8',
            'home': '0',
            'away': '1'
          },
          {
            'inning': '9',
            'home': 'x',
            'away': '0'
          }
        ],
        'home_team_errors': '0',
        'away_team_errors': '1',
        'home_team_hits': '9',
        'away_team_hits': '8',
        'home_team_runs': '7',
        'away_team_runs': '3'
      },
      'pitching': [
        {
          'pitcher': [
            {
              'id': '527054',
              's': '52',
              'era': '4.71',
              'er': '5',
              'hr': '2',
              'bf': '22',
              'so': '4',
              'bb': '4',
              'r': '5',
              'h': '5',
              'out': '12',
              'loss': 'true',
              'note': '(L, 6-6)',
              's_so': '106',
              's_bb': '49',
              's_er': '65',
              's_r': '74',
              's_h': '125',
              's_ip': '124.1',
              'hld': '0',
              'bs': '0',
              'sv': '0',
              'l': '6',
              'w': '6',
              'np': '92',
              'pos': 'P',
              'name_display_first_last': 'Julio Teheran',
              'name': 'Teheran'
            },
            {
              'id': '446321',
              's': '21',
              'era': '6.85',
              'er': '1',
              'hr': '0',
              'bf': '8',
              'so': '1',
              'bb': '0',
              'r': '2',
              'h': '4',
              'out': '3',
              's_so': '30',
              's_bb': '21',
              's_er': '35',
              's_r': '39',
              's_h': '67',
              's_ip': '46.0',
              'hld': '1',
              'bs': '1',
              'sv': '0',
              'l': '5',
              'w': '0',
              'np': '35',
              'pos': 'P',
              'name_display_first_last': 'Ross Detwiler',
              'name': 'Detwiler'
            },
            {
              'id': '605374',
              's': '18',
              'era': '2.45',
              'er': '0',
              'hr': '0',
              'bf': '6',
              'so': '3',
              'bb': '0',
              'r': '0',
              'h': '0',
              'out': '6',
              's_so': '7',
              's_bb': '1',
              's_er': '2',
              's_r': '2',
              's_h': '6',
              's_ip': '7.1',
              'hld': '1',
              'bs': '0',
              'sv': '0',
              'l': '0',
              'w': '0',
              'np': '21',
              'pos': 'P',
              'name_display_first_last': 'Andrew McKirahan',
              'name': 'McKirahan'
            },
            {
              'id': '430911',
              's': '5',
              'era': '2.00',
              'er': '0',
              'hr': '0',
              'bf': '3',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              'out': '3',
              's_so': '20',
              's_bb': '9',
              's_er': '4',
              's_r': '4',
              's_h': '11',
              's_ip': '18.0',
              'hld': '3',
              'bs': '2',
              'sv': '0',
              'l': '0',
              'w': '0',
              'np': '5',
              'pos': 'P',
              'name_display_first_last': 'David Aardsma',
              'name': 'Aardsma'
            }
          ],
          'era': '3.92',
          'er': '6',
          'hr': '2',
          'bf': '39',
          'so': '8',
          'bb': '4',
          'r': '7',
          'h': '9',
          'out': '24',
          'team_flag': 'away'
        },
        {
          'pitcher': [
            {
              'id': '434622',
              's': '62',
              'era': '3.73',
              'er': '2',
              'hr': '1',
              'bf': '29',
              'so': '3',
              'bb': '3',
              'r': '2',
              'h': '4',
              'out': '21',
              'note': '(W, 8-6)',
              's_so': '108',
              's_bb': '38',
              's_er': '47',
              's_r': '50',
              's_h': '113',
              's_ip': '113.1',
              'hld': '0',
              'bs': '0',
              'sv': '0',
              'l': '6',
              'w': '8',
              'np': '106',
              'win': 'true',
              'pos': 'P',
              'name_display_first_last': 'Ubaldo Jimenez',
              'name': 'Jiménez'
            },
            {
              'id': '451085',
              's': '6',
              'era': '2.56',
              'er': '1',
              'hr': '0',
              'bf': '3',
              'so': '0',
              'bb': '0',
              'r': '1',
              'h': '1',
              'out': '2',
              's_so': '35',
              's_bb': '16',
              's_er': '9',
              's_r': '10',
              's_h': '24',
              's_ip': '31.2',
              'hld': '1',
              'bs': '0',
              'sv': '0',
              'l': '2',
              'w': '1',
              'np': '6',
              'pos': 'P',
              'name_display_first_last': 'Brian Matusz',
              'name': 'Matusz'
            },
            {
              'id': '475054',
              's': '16',
              'era': '2.20',
              'er': '0',
              'hr': '0',
              'bf': '7',
              'so': '1',
              'bb': '0',
              'r': '0',
              'h': '3',
              'out': '4',
              's_so': '33',
              's_bb': '10',
              's_er': '8',
              's_r': '8',
              's_h': '28',
              's_ip': '32.2',
              'hld': '3',
              'bs': '0',
              'sv': '0',
              'l': '1',
              'w': '2',
              'np': '23',
              'pos': 'P',
              'name_display_first_last': 'Chaz Roe',
              'name': 'Roe'
            }
          ],
          'era': '3.70',
          'er': '3',
          'hr': '1',
          'bf': '39',
          'so': '4',
          'bb': '3',
          'r': '3',
          'h': '8',
          'out': '27',
          'team_flag': 'home'
        }
      ],
      'batting': [
        {
          'batter': [
            {
              'id': '592518',
              'hr': '0',
              'so': '1',
              'bb': '0',
              'r': '2',
              'h': '1',
              's_so': '67',
              's_bb': '42',
              's_r': '62',
              's_h': '110',
              'pos': '3B',
              'name_display_first_last': 'Manny Machado',
              'name': 'Machado',
              'ops': '.872',
              'slg': '.513',
              'obp': '.359',
              'avg': '.289',
              'lob': '1',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '5',
              'ao': '1',
              's_rbi': '51',
              's_hr': '21',
              'cs': '0',
              'sb': '0',
              'fldg': '.962',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '3',
              'bo': '100',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '517370',
              'hr': '0',
              'so': '1',
              'bb': '1',
              'r': '1',
              'h': '1',
              's_so': '84',
              's_bb': '15',
              's_r': '39',
              's_h': '83',
              'pos': 'DH',
              'name_display_first_last': 'Jimmy Paredes',
              'name': 'Paredes, J',
              'ops': '.773',
              'slg': '.451',
              'obp': '.321',
              'avg': '.288',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '39',
              's_hr': '10',
              'cs': '0',
              'sb': '0',
              'fldg': '.939',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '200',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '430945',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '1',
              'h': '2',
              's_so': '54',
              's_bb': '16',
              's_r': '49',
              's_h': '101',
              'pos': 'CF',
              'name_display_first_last': 'Adam Jones',
              'name': 'Jones, A',
              'ops': '.817',
              'slg': '.487',
              'obp': '.330',
              'avg': '.289',
              'lob': '2',
              'po': '2',
              'rbi': '1',
              't': '0',
              'd': '1',
              'ab': '5',
              'ao': '0',
              's_rbi': '45',
              's_hr': '15',
              'cs': '0',
              'sb': '0',
              'fldg': '.991',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '300',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '448801',
              'hr': '2',
              'so': '0',
              'bb': '0',
              'r': '2',
              'h': '2',
              's_so': '123',
              's_bb': '43',
              's_r': '51',
              's_h': '85',
              'pos': 'RF',
              'name_display_first_last': 'Chris Davis',
              'name': 'Davis, C',
              'ops': '.822',
              'slg': '.497',
              'obp': '.325',
              'avg': '.243',
              'lob': '2',
              'po': '1',
              'rbi': '5',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '65',
              's_hr': '24',
              'cs': '0',
              'sb': '0',
              'fldg': '.996',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '400',
              'go': '2',
              'gidp': '0'
            },
            {
              'id': '501983',
              'hr': '0',
              'so': '1',
              'bb': '0',
              'r': '0',
              'h': '1',
              's_so': '54',
              's_bb': '22',
              's_r': '23',
              's_h': '50',
              'pos': 'LF',
              'name_display_first_last': 'Travis Snider',
              'name': 'Snider',
              'ops': '.662',
              'slg': '.344',
              'obp': '.318',
              'avg': '.239',
              'lob': '2',
              'po': '3',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '3',
              'ao': '0',
              's_rbi': '20',
              's_hr': '3',
              'cs': '0',
              'sb': '0',
              'fldg': '.991',
              'hbp': '1',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '500',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '570731',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '21',
              's_bb': '3',
              's_r': '9',
              's_h': '21',
              'pos': '2B',
              'name_display_first_last': 'Jonathan Schoop',
              'name': 'Schoop',
              'ops': '.823',
              'slg': '.525',
              'obp': '.298',
              'avg': '.263',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '14',
              's_hr': '6',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '2',
              'bo': '501',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '429666',
              'hr': '0',
              'so': '1',
              'bb': '0',
              'r': '1',
              'h': '1',
              's_so': '52',
              's_bb': '12',
              's_r': '33',
              's_h': '60',
              'pos': 'SS',
              'name_display_first_last': 'J.J. Hardy',
              'name': 'Hardy',
              'ops': '.613',
              'slg': '.343',
              'obp': '.271',
              'avg': '.239',
              'lob': '4',
              'po': '1',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '28',
              's_hr': '6',
              'cs': '0',
              'sb': '0',
              'fldg': '.996',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '5',
              'bo': '600',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '476633',
              'hr': '0',
              'so': '2',
              'bb': '1',
              'r': '0',
              'h': '0',
              's_so': '25',
              's_bb': '4',
              's_r': '11',
              's_h': '20',
              'pos': '1B',
              'name_display_first_last': 'Chris Parmelee',
              'name': 'Parmelee',
              'ops': '.696',
              'slg': '.441',
              'obp': '.255',
              'avg': '.215',
              'lob': '1',
              'po': '11',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '3',
              'ao': '0',
              's_rbi': '9',
              's_hr': '4',
              'cs': '0',
              'sb': '0',
              'fldg': '.995',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '700',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '543376',
              'hr': '0',
              'so': '1',
              'bb': '2',
              'r': '0',
              'h': '1',
              's_so': '50',
              's_bb': '21',
              's_r': '25',
              's_h': '49',
              'pos': 'C',
              'name_display_first_last': 'Caleb Joseph',
              'name': 'Joseph',
              'ops': '.715',
              'slg': '.396',
              'obp': '.319',
              'avg': '.243',
              'lob': '0',
              'po': '4',
              'rbi': '1',
              't': '0',
              'd': '0',
              'ab': '2',
              'ao': '0',
              's_rbi': '31',
              's_hr': '7',
              'cs': '0',
              'sb': '0',
              'fldg': '.998',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '800',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '475247',
              'hr': '0',
              'so': '1',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '55',
              's_bb': '16',
              's_r': '23',
              's_h': '41',
              'pos': '2B',
              'name_display_first_last': 'Ryan Flaherty',
              'name': 'Flaherty, R',
              'ops': '.656',
              'slg': '.357',
              'obp': '.299',
              'avg': '.225',
              'lob': '5',
              'po': '3',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '22',
              's_hr': '4',
              'cs': '0',
              'sb': '0',
              'fldg': '.996',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '900',
              'go': '2',
              'gidp': '0'
            },
            {
              'id': '518953',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '30',
              's_bb': '4',
              's_r': '13',
              's_h': '26',
              'pos': 'LF',
              'name_display_first_last': 'David Lough',
              'name': 'Lough',
              'ops': '.600',
              'slg': '.345',
              'obp': '.256',
              'avg': '.218',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '12',
              's_hr': '4',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '901',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '434622',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '2',
              's_bb': '0',
              's_r': '0',
              's_h': '1',
              'pos': 'P',
              'name_display_first_last': 'Ubaldo Jimenez',
              'name': 'Jiménez',
              'ops': '.400',
              'slg': '.200',
              'obp': '.200',
              'avg': '.200',
              'lob': '0',
              'po': '2',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '1',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '451085',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '0',
              's_bb': '0',
              's_r': '0',
              's_h': '0',
              'pos': 'P',
              'name_display_first_last': 'Brian Matusz',
              'name': 'Matusz',
              'ops': '.000',
              'slg': '.000',
              'obp': '.000',
              'avg': '.000',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '0',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '475054',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '0',
              's_bb': '0',
              's_r': '0',
              's_h': '0',
              'pos': 'P',
              'name_display_first_last': 'Chaz Roe',
              'name': 'Roe',
              'ops': '.000',
              'slg': '.000',
              'obp': '.000',
              'avg': '.000',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '0',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '',
              'go': '0',
              'gidp': '0'
            }
          ],
          'text_data': '<br/><b>BATTING</b><br/><b>2B</b>: Jones, A (18, Detwiler).<br/><b>HR</b>: Davis, C 2 (24, 1st inning off Teheran, 2 on, 1 out, 2nd inning off Teheran, 1 on, 2 out).<br/><b>TB</b>: Davis, C 8; Hardy; Jones, A 3; Joseph; Machado; Paredes, J; Snider.<br/><b>RBI</b>: Davis, C 5 (65); Jones, A (45); Joseph (31).<br/><b>2-out RBI</b>: Davis, C 2; Joseph.<br/><b>Runners left in scoring position, 2 out</b>: Hardy 2; Flaherty, R 2; Machado.<br/><b>Team RISP</b>: 3-for-9.<br/><b>Team LOB</b>: 8.<br/><br/>',
          'text_data_es': '<br/><b>Bateo</b><br/><b>2B</b>: Jones, A (18, Detwiler).<br/><b>HR</b>: Davis, C 2 (24, 1st entrada ante Teheran, 2 en base, 1 out, 2nd entrada ante Teheran, 1 en base, 2 out).<br/><b>BA</b>: Davis, C 8; Hardy; Jones, A 3; Joseph; Machado; Paredes, J; Snider.<br/><b>CE</b>: Davis, C 5 (65); Jones, A (45); Joseph (31).<br/><b>2-out RBI</b>: Davis, C 2; Joseph.<br/><b>Corredores dejados en circulacion, 2 out</b>: Hardy 2; Flaherty, R 2; Machado.<br/><b>Equipo con Corredores en Posicion de Anotar</b>: de 3-9.<br/><b>Equipo con Corredores Dejados en Circulacion</b>: 8.<br/><br/>',
          'hr': '2',
          'so': '8',
          'bb': '4',
          'r': '7',
          'h': '9',
          'team_flag': 'home',
          'ops': '.727',
          'slg': '.419',
          'obp': '.308',
          'avg': '.253',
          'lob': '17',
          'da': '14',
          'po': '27',
          'rbi': '7',
          't': '0',
          'd': '1',
          'ab': '34'
        },
        {
          'batter': [
            {
              'id': '455976',
              'hr': '0',
              'so': '1',
              'bb': '1',
              'r': '1',
              'h': '2',
              's_so': '57',
              's_bb': '47',
              's_r': '43',
              's_h': '110',
              'pos': 'RF',
              'name_display_first_last': 'Nick Markakis',
              'name': 'Markakis',
              'ops': '.736',
              'slg': '.364',
              'obp': '.371',
              'avg': '.290',
              'lob': '2',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '32',
              's_hr': '1',
              'cs': '0',
              'sb': '0',
              'fldg': '.995',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '100',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '457727',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '65',
              's_bb': '31',
              's_r': '42',
              's_h': '89',
              'pos': 'CF',
              'name_display_first_last': 'Cameron Maybin',
              'name': 'Maybin',
              'ops': '.723',
              'slg': '.387',
              'obp': '.336',
              'avg': '.273',
              'lob': '4',
              'po': '2',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '5',
              'ao': '0',
              's_rbi': '47',
              's_hr': '8',
              'cs': '0',
              'sb': '0',
              'fldg': '.991',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '200',
              'go': '5',
              'gidp': '0'
            },
            {
              'id': '518692',
              'hr': '1',
              'so': '1',
              'bb': '0',
              'r': '1',
              'h': '1',
              's_so': '66',
              's_bb': '27',
              's_r': '44',
              's_h': '78',
              'pos': '1B',
              'name_display_first_last': 'Freddie Freeman',
              'name': 'Freeman',
              'ops': '.870',
              'slg': '.511',
              'obp': '.359',
              'avg': '.291',
              'lob': '2',
              'po': '9',
              'rbi': '2',
              't': '0',
              'd': '0',
              'ab': '5',
              'ao': '2',
              's_rbi': '43',
              's_hr': '13',
              'cs': '0',
              'sb': '0',
              'fldg': '.993',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '300',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '611177',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '1',
              'h': '1',
              's_so': '4',
              's_bb': '1',
              's_r': '3',
              's_h': '5',
              'pos': '3B',
              'name_display_first_last': 'Adonis Garcia',
              'name': 'García, A',
              'ops': '1.039',
              'slg': '.706',
              'obp': '.333',
              'avg': '.294',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '2',
              's_hr': '2',
              'cs': '0',
              'sb': '0',
              'fldg': '.889',
              'hbp': '0',
              'e': '1',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '400',
              'go': '3',
              'gidp': '0'
            },
            {
              'id': '150229',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '1',
              's_so': '25',
              's_bb': '12',
              's_r': '26',
              's_h': '72',
              'pos': 'C',
              'name_display_first_last': 'A.J. Pierzynski',
              'name': 'Pierzynski',
              'ops': '.748',
              'slg': '.425',
              'obp': '.322',
              'avg': '.283',
              'lob': '1',
              'po': '8',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '2',
              's_rbi': '30',
              's_hr': '6',
              'cs': '0',
              'sb': '0',
              'fldg': '.996',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '500',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '430404',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '2',
              's_so': '53',
              's_bb': '22',
              's_r': '20',
              's_h': '33',
              'pos': 'LF',
              'name_display_first_last': 'Jonny Gomes',
              'name': 'Gomes, J',
              'ops': '.632',
              'slg': '.323',
              'obp': '.309',
              'avg': '.205',
              'lob': '0',
              'po': '2',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '13',
              's_hr': '4',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '600',
              'go': '2',
              'gidp': '0'
            },
            {
              'id': '607054',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '1',
              's_so': '77',
              's_bb': '39',
              's_r': '35',
              's_h': '83',
              'pos': '2B',
              'name_display_first_last': 'Jace Peterson',
              'name': 'Peterson',
              'ops': '.663',
              'slg': '.338',
              'obp': '.325',
              'avg': '.244',
              'lob': '0',
              'po': '1',
              'rbi': '1',
              't': '0',
              'd': '0',
              'ab': '3',
              'ao': '0',
              's_rbi': '41',
              's_hr': '3',
              'cs': '0',
              'sb': '0',
              'fldg': '.985',
              'hbp': '1',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '2',
              'bo': '700',
              'go': '2',
              'gidp': '0'
            },
            {
              'id': '453400',
              'hr': '0',
              'so': '2',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '43',
              's_bb': '6',
              's_r': '9',
              's_h': '31',
              'pos': 'DH',
              'name_display_first_last': 'Chris Johnson',
              'name': 'Johnson, C',
              'ops': '.578',
              'slg': '.308',
              'obp': '.270',
              'avg': '.233',
              'lob': '5',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '4',
              'ao': '0',
              's_rbi': '9',
              's_hr': '1',
              'cs': '0',
              'sb': '0',
              'fldg': '.967',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '800',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '592743',
              'hr': '0',
              'so': '0',
              'bb': '2',
              'r': '0',
              'h': '0',
              's_so': '28',
              's_bb': '28',
              's_r': '48',
              's_h': '92',
              'pos': 'SS',
              'name_display_first_last': 'Andrelton Simmons',
              'name': 'Simmons',
              'ops': '.660',
              'slg': '.337',
              'obp': '.323',
              'avg': '.258',
              'lob': '0',
              'po': '2',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '2',
              'ao': '0',
              's_rbi': '30',
              's_hr': '3',
              'cs': '0',
              'sb': '0',
              'fldg': '.993',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '900',
              'go': '1',
              'gidp': '0'
            },
            {
              'id': '527054',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '4',
              's_bb': '1',
              's_r': '0',
              's_h': '2',
              'pos': 'P',
              'name_display_first_last': 'Julio Teheran',
              'name': 'Teheran',
              'ops': '.153',
              'slg': '.063',
              'obp': '.091',
              'avg': '.063',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '2',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '.966',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '446321',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '0',
              's_bb': '0',
              's_r': '0',
              's_h': '0',
              'pos': 'P',
              'name_display_first_last': 'Ross Detwiler',
              'name': 'Detwiler',
              'ops': '.000',
              'slg': '.000',
              'obp': '.000',
              'avg': '.000',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '0',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '1',
              'bo': '',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '605374',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '0',
              's_bb': '0',
              's_r': '0',
              's_h': '0',
              'pos': 'P',
              'name_display_first_last': 'Andrew McKirahan',
              'name': 'McKirahan',
              'ops': '.000',
              'slg': '.000',
              'obp': '.000',
              'avg': '.000',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '0',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '1.000',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '',
              'go': '0',
              'gidp': '0'
            },
            {
              'id': '430911',
              'hr': '0',
              'so': '0',
              'bb': '0',
              'r': '0',
              'h': '0',
              's_so': '1',
              's_bb': '0',
              's_r': '0',
              's_h': '0',
              'pos': 'P',
              'name_display_first_last': 'David Aardsma',
              'name': 'Aardsma',
              'ops': '.000',
              'slg': '.000',
              'obp': '.000',
              'avg': '.000',
              'lob': '0',
              'po': '0',
              'rbi': '0',
              't': '0',
              'd': '0',
              'ab': '0',
              'ao': '0',
              's_rbi': '0',
              's_hr': '0',
              'cs': '0',
              'sb': '0',
              'fldg': '.500',
              'hbp': '0',
              'e': '0',
              'sf': '0',
              'sac': '0',
              'a': '0',
              'bo': '',
              'go': '0',
              'gidp': '0'
            }
          ],
          'text_data': '<br/><b>BATTING</b><br/><b>HR</b>: Freeman (13, 1st inning off Jiménez, 1 on, 1 out).<br/><b>TB</b>: Freeman 4; García, A; Gomes, J 2; Markakis 2; Peterson; Pierzynski.<br/><b>RBI</b>: Freeman 2 (43); Peterson (41).<br/><b>2-out RBI</b>: Peterson.<br/><b>Runners left in scoring position, 2 out</b>: Johnson, C 3; Markakis.<br/><b>Team RISP</b>: 2-for-5.<br/><b>Team LOB</b>: 9.<br/><br/><b>FIELDING</b><br/><b>E</b>: García, A (1, fielding).<br/><br/>',
          'text_data_es': '<br/><b>Bateo</b><br/><b>HR</b>: Freeman (13, 1st entrada ante Jiménez, 1 en base, 1 out).<br/><b>BA</b>: Freeman 4; García, A; Gomes, J 2; Markakis 2; Peterson; Pierzynski.<br/><b>CE</b>: Freeman 2 (43); Peterson (41).<br/><b>2-out RBI</b>: Peterson.<br/><b>Corredores dejados en circulacion, 2 out</b>: Johnson, C 3; Markakis.<br/><b>Equipo con Corredores en Posicion de Anotar</b>: de 2-5.<br/><b>Equipo con Corredores Dejados en Circulacion</b>: 9.<br/><br/><b>Defensa</b><br/><b>E</b>: García, A (1, fielding).<br/><br/>',
          'hr': '1',
          'so': '4',
          'bb': '3',
          'r': '3',
          'h': '8',
          'team_flag': 'away',
          'ops': '.675',
          'slg': '.361',
          'obp': '.314',
          'avg': '.251',
          'lob': '14',
          'da': '0',
          'po': '0',
          'rbi': '3',
          't': '0',
          'd': '0',
          'ab': '35'
        }
      ],
      'game_info': '<span>Detwiler pitched to 3 batters in the 6th.</span><br/><br/><b>WP</b>: Jiménez.<br/><b>HBP</b>: Peterson (by Jiménez); Snider (by Teheran).<br/><b>Pitches-strikes</b>: Teheran 92-52; Detwiler 35-21; McKirahan 21-18; Aardsma 5-5; Jiménez 106-62; Matusz 6-6; Roe 23-16.<br/><b>Groundouts-flyouts</b>: Teheran 3-1; Detwiler 3-0; McKirahan 1-0; Aardsma 0-0; Jiménez 12-2; Matusz 0-2; Roe 3-0.<br/><b>Batters faced</b>: Teheran 22; Detwiler 8; McKirahan 6; Aardsma 3; Jiménez 29; Matusz 3; Roe 7.<br/><b>Inherited runners-scored</b>: McKirahan 2-0; Roe 1-1.<br/><b>Umpires</b>: HP: Scott Barry. 1B: Jim Wolf. 2B: Chris Conroy. 3B: Angel Hernandez. <br/><b>Weather</b>: 86 degrees, Clear.<br/><b>Wind</b>: 6 mph, Out To LF.<br/><b>First pitch</b>: 7:07 PM.<br/><b>T</b>: 2:53.<br/><b>Att</b>: 28,592.<br/><b>Venue</b>: Oriole Park at Camden Yards.<br/><b>July 28, 2015</b><br/>',
      'game_info_es': '<span>Detwiler enfrento 3 bateadores en la 6th.</span><br/><br/><b>WP</b>: Jiménez.<br/><b>BG</b>: Peterson (by Jiménez); Snider (by Teheran).<br/><b>Lanzamientos-strikes</b>: Teheran 92-52; Detwiler 35-21; McKirahan 21-18; Aardsma 5-5; Jiménez 106-62; Matusz 6-6; Roe 23-16.<br/><b>Roletazos-elevados de out</b>: Teheran 3-1; Detwiler 3-0; McKirahan 1-0; Aardsma 0-0; Jiménez 12-2; Matusz 0-2; Roe 3-0.<br/><b>Bateadores enfrentados</b>: Teheran 22; Detwiler 8; McKirahan 6; Aardsma 3; Jiménez 29; Matusz 3; Roe 7.<br/><b>Corredores Heredados que Anotaron</b>: McKirahan 2-0; Roe 1-1.<br/><b>Arbitros</b>: HP: Scott Barry. 1B: Jim Wolf. 2B: Chris Conroy. 3B: Angel Hernandez. <br/><b>Weather</b>: 86 degrees, Clear.<br/><b>Wind</b>: 6 mph, Out To LF.<br/><b>First pitch</b>: 7:07 PM.<br/><b>T</b>: 2:53.<br/><b>Att</b>: 28,592.<br/><b>Estadio</b>: Oriole Park at Camden Yards.<br/><b>July 28, 2015</b><br/>',
      'away_loss': '54',
      'home_loss': '49',
      'status_ind': 'F',
      'date': 'July 28, 2015',
      'home_wins': '50',
      'away_wins': '46',
      'home_sname': 'Baltimore',
      'away_sname': 'Atlanta',
      'home_fname': 'Baltimore Orioles',
      'away_fname': 'Atlanta Braves',
      'home_id': '110',
      'away_id': '144',
      'home_team_code': 'bal',
      'away_team_code': 'atl',
      'home_sport_code': 'mlb',
      'venue_id': '2',
      'venue_name': 'Oriole Park at Camden Yards',
      'game_pk': '415140',
      'game_id': '2015/07/28/atlmlb-balmlb-1'
    }
  }
}

export default (state = initialState, { type, payload }) => {
  switch (type) {
    case 'SET_SELECTED_RESULT':
      return { ...state, ...payload }

    default:
      return state
  }
}
